# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_sun_input.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(344, 244)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(21, 90, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.cb_zhi = QtGui.QLineEdit(Dialog)
        self.cb_zhi.setGeometry(QtCore.QRect(60, 90, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_zhi.setFont(font)
        self.cb_zhi.setObjectName(_fromUtf8("cb_zhi"))
        self.cb_quan = QtGui.QLineEdit(Dialog)
        self.cb_quan.setGeometry(QtCore.QRect(60, 120, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_quan.setFont(font)
        self.cb_quan.setObjectName(_fromUtf8("cb_quan"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(21, 120, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(21, 150, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cb_dai = QtGui.QLineEdit(Dialog)
        self.cb_dai.setGeometry(QtCore.QRect(60, 150, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_dai.setFont(font)
        self.cb_dai.setObjectName(_fromUtf8("cb_dai"))
        self.cb_la = QtGui.QLineEdit(Dialog)
        self.cb_la.setGeometry(QtCore.QRect(60, 180, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_la.setFont(font)
        self.cb_la.setObjectName(_fromUtf8("cb_la"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(21, 180, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(180, 120, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(21, 210, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cq_zhu = QtGui.QLineEdit(Dialog)
        self.cq_zhu.setGeometry(QtCore.QRect(230, 90, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cq_zhu.setFont(font)
        self.cq_zhu.setObjectName(_fromUtf8("cq_zhu"))
        self.cq_tiesi = QtGui.QLineEdit(Dialog)
        self.cq_tiesi.setGeometry(QtCore.QRect(230, 120, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cq_tiesi.setFont(font)
        self.cq_tiesi.setObjectName(_fromUtf8("cq_tiesi"))
        self.cb_kmd = QtGui.QLineEdit(Dialog)
        self.cb_kmd.setGeometry(QtCore.QRect(60, 210, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb_kmd.setFont(font)
        self.cb_kmd.setObjectName(_fromUtf8("cb_kmd"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(180, 90, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.csure = QtGui.QPushButton(Dialog)
        self.csure.setGeometry(QtCore.QRect(230, 195, 100, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        self.csure.setFont(font)
        self.csure.setObjectName(_fromUtf8("csure"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(180, 60, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cid = QtGui.QLabel(Dialog)
        self.cid.setGeometry(QtCore.QRect(15, 0, 31, 16))
        self.cid.setText(_fromUtf8(""))
        self.cid.setObjectName(_fromUtf8("cid"))
        self.cname = QtGui.QLabel(Dialog)
        self.cname.setGeometry(QtCore.QRect(21, 15, 130, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(20)
        self.cname.setFont(font)
        self.cname.setText(_fromUtf8(""))
        self.cname.setObjectName(_fromUtf8("cname"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(21, 60, 45, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.dateEdit = QtGui.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(60, 60, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.cev_id = QtGui.QLabel(Dialog)
        self.cev_id.setGeometry(QtCore.QRect(230, 60, 100, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Sans"))
        font.setPointSize(12)
        self.cev_id.setFont(font)
        self.cev_id.setText(_fromUtf8(""))
        self.cev_id.setObjectName(_fromUtf8("cev_id"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.csure, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.slot_btn_sure)
        QtCore.QObject.connect(self.dateEdit, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), Dialog.slot_date_changed)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.cb_zhi, self.cb_quan)
        Dialog.setTabOrder(self.cb_quan, self.cb_dai)
        Dialog.setTabOrder(self.cb_dai, self.cb_la)
        Dialog.setTabOrder(self.cb_la, self.cb_kmd)
        Dialog.setTabOrder(self.cb_kmd, self.cq_zhu)
        Dialog.setTabOrder(self.cq_zhu, self.cq_tiesi)
        Dialog.setTabOrder(self.cq_tiesi, self.csure)
        Dialog.setTabOrder(self.csure, self.dateEdit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "半纸", None))
        self.label_2.setText(_translate("Dialog", "竹圈", None))
        self.label_3.setText(_translate("Dialog", "袋子", None))
        self.label_4.setText(_translate("Dialog", "蜡", None))
        self.label_5.setText(_translate("Dialog", "铁丝", None))
        self.label_6.setText(_translate("Dialog", "灯", None))
        self.label_7.setText(_translate("Dialog", "竹子", None))
        self.csure.setText(_translate("Dialog", "确定", None))
        self.label_8.setText(_translate("Dialog", "事件ID", None))
        self.label_9.setText(_translate("Dialog", "日期", None))

