# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_huo.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(399, 265)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(205, 20, 61, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(15, 60, 54, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(205, 60, 54, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(15, 20, 61, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cty = QtGui.QComboBox(Dialog)
        self.cty.setGeometry(QtCore.QRect(270, 20, 112, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cty.setFont(font)
        self.cty.setEditable(True)
        self.cty.setObjectName(_fromUtf8("cty"))
        self.cpay = QtGui.QLineEdit(Dialog)
        self.cpay.setGeometry(QtCore.QRect(80, 60, 116, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cpay.setFont(font)
        self.cpay.setObjectName(_fromUtf8("cpay"))
        self.cnums = QtGui.QLineEdit(Dialog)
        self.cnums.setGeometry(QtCore.QRect(270, 60, 112, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cnums.setFont(font)
        self.cnums.setObjectName(_fromUtf8("cnums"))
        self.ctext = QtGui.QTextEdit(Dialog)
        self.ctext.setGeometry(QtCore.QRect(15, 150, 368, 106))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ctext.setFont(font)
        self.ctext.setObjectName(_fromUtf8("ctext"))
        self.cdate = QtGui.QDateEdit(Dialog)
        self.cdate.setGeometry(QtCore.QRect(80, 20, 116, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cdate.setFont(font)
        self.cdate.setCalendarPopup(True)
        self.cdate.setObjectName(_fromUtf8("cdate"))
        self.cvalid = QtGui.QCheckBox(Dialog)
        self.cvalid.setGeometry(QtCore.QRect(15, 105, 60, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cvalid.setFont(font)
        self.cvalid.setChecked(True)
        self.cvalid.setObjectName(_fromUtf8("cvalid"))
        self.csure = QtGui.QPushButton(Dialog)
        self.csure.setGeometry(QtCore.QRect(270, 105, 112, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.csure.setFont(font)
        self.csure.setObjectName(_fromUtf8("csure"))
        self.cIsLa = QtGui.QCheckBox(Dialog)
        self.cIsLa.setGeometry(QtCore.QRect(135, 105, 60, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cIsLa.setFont(font)
        self.cIsLa.setObjectName(_fromUtf8("cIsLa"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.csure, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.slot_sure)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.cpay, self.cnums)
        Dialog.setTabOrder(self.cnums, self.cvalid)
        Dialog.setTabOrder(self.cvalid, self.cIsLa)
        Dialog.setTabOrder(self.cIsLa, self.ctext)
        Dialog.setTabOrder(self.ctext, self.csure)
        Dialog.setTabOrder(self.csure, self.cdate)
        Dialog.setTabOrder(self.cdate, self.cty)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "货物类型", None))
        self.label_2.setText(_translate("Dialog", "单价", None))
        self.label_3.setText(_translate("Dialog", "数量", None))
        self.label_5.setText(_translate("Dialog", "创建日期", None))
        self.cvalid.setText(_translate("Dialog", "有效", None))
        self.csure.setText(_translate("Dialog", "确定", None))
        self.cIsLa.setText(_translate("Dialog", "含腊", None))

