# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ev.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(379, 339)
        self.cSh = QtGui.QLineEdit(Dialog)
        self.cSh.setGeometry(QtCore.QRect(59, 98, 113, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cSh.setFont(font)
        self.cSh.setObjectName(_fromUtf8("cSh"))
        self.cFa = QtGui.QLineEdit(Dialog)
        self.cFa.setGeometry(QtCore.QRect(59, 139, 113, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cFa.setFont(font)
        self.cFa.setObjectName(_fromUtf8("cFa"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(15, 103, 30, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(15, 143, 30, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(15, 180, 30, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cSun = QtGui.QLineEdit(Dialog)
        self.cSun.setGeometry(QtCore.QRect(59, 180, 113, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cSun.setFont(font)
        self.cSun.setObjectName(_fromUtf8("cSun"))
        self.cMoney = QtGui.QLineEdit(Dialog)
        self.cMoney.setGeometry(QtCore.QRect(255, 98, 113, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cMoney.setFont(font)
        self.cMoney.setObjectName(_fromUtf8("cMoney"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(194, 103, 30, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lab_la = QtGui.QLabel(Dialog)
        self.lab_la.setGeometry(QtCore.QRect(194, 143, 30, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.lab_la.setFont(font)
        self.lab_la.setObjectName(_fromUtf8("lab_la"))
        self.cLa = QtGui.QLineEdit(Dialog)
        self.cLa.setGeometry(QtCore.QRect(255, 140, 113, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cLa.setFont(font)
        self.cLa.setObjectName(_fromUtf8("cLa"))
        self.cAdd = QtGui.QPushButton(Dialog)
        self.cAdd.setGeometry(QtCore.QRect(262, 180, 106, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cAdd.setFont(font)
        self.cAdd.setObjectName(_fromUtf8("cAdd"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(194, 68, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(15, 68, 31, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cDate = QtGui.QDateEdit(Dialog)
        self.cDate.setGeometry(QtCore.QRect(59, 59, 117, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(11)
        self.cDate.setFont(font)
        self.cDate.setCalendarPopup(True)
        self.cDate.setObjectName(_fromUtf8("cDate"))
        self.cHuoBox = QtGui.QComboBox(Dialog)
        self.cHuoBox.setGeometry(QtCore.QRect(255, 60, 113, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cHuoBox.setFont(font)
        self.cHuoBox.setObjectName(_fromUtf8("cHuoBox"))
        self.cText = QtGui.QTextEdit(Dialog)
        self.cText.setGeometry(QtCore.QRect(15, 225, 350, 106))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cText.setFont(font)
        self.cText.setObjectName(_fromUtf8("cText"))
        self.cName = QtGui.QLabel(Dialog)
        self.cName.setGeometry(QtCore.QRect(15, 15, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(20)
        self.cName.setFont(font)
        self.cName.setObjectName(_fromUtf8("cName"))
        self.ccheck = QtGui.QCheckBox(Dialog)
        self.ccheck.setGeometry(QtCore.QRect(194, 180, 50, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.ccheck.setFont(font)
        self.ccheck.setObjectName(_fromUtf8("ccheck"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.cAdd, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.slot_add)
        QtCore.QObject.connect(self.cHuoBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Dialog.slot_chuobox_index_changed)
        QtCore.QObject.connect(self.cSh, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Dialog.slot_csh_finished)
        QtCore.QObject.connect(self.cDate, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), Dialog.slot_date_changed)
        QtCore.QObject.connect(self.ccheck, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Dialog.slot_state_changed)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "收货", None))
        self.label_2.setText(_translate("Dialog", "发货", None))
        self.label_3.setText(_translate("Dialog", "损耗", None))
        self.label_4.setText(_translate("Dialog", "付钱", None))
        self.lab_la.setText(_translate("Dialog", "蜡", None))
        self.cAdd.setText(_translate("Dialog", "添加", None))
        self.label_12.setText(_translate("Dialog", "货物ID", None))
        self.label_13.setText(_translate("Dialog", "日期", None))
        self.cName.setText(_translate("Dialog", "--", None))
        self.ccheck.setText(_translate("Dialog", "检", None))
